### ISSUE TITLE
VSAN Performance Metrics

### ISSUE THREAD

**Issue by Rajupln917** [newrelic/nri-vsphere#198]
Is it possible to have vSAN performance related metrics such as  IOPS, throughput, and latency etc.,?

Reference documents: 

https://blogs.vmware.com/virtualblocks/2019/06/12/vsan-performance-metric-levels/
https://docs.vmware.com/en/vRealize-Operations/8.10/com.vmware.vcom.metrics.doc/GUID-73B4D48A-CDE8-458C-B993-09956274B073.html

**Comment by kang-makes** [comment]
Hi!

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs.

To give you a glance of a solution, you are looking for vSphere performance metrics: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration/#perf-metrics

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
