### ISSUE TITLE
additional functionality

### ISSUE THREAD

**Issue by sdeedee** [newrelic/nri-vsphere#20]
Nice update on the old vmware ohi. Any change you add snapshot info and/or DRS/HA settings on the cluster also to this new integration? I think this can be very useful in dashboard overview/from alerting perspective.

thanks.

**Comment by paologallinaharbur** [comment]
Thanks for the feedback. Right now the integration does not fetch such data. 

However, I opened a new separate issue for each feature request you mentioned. 
We are going to follow up there in case we have any new information.
