### ISSUE TITLE
level=fatal msg="failed to publish" 

### ISSUE THREAD

**Issue by Midnigh7** [newrelic/nri-vsphere#27]
Just configured, and am getting this message.

time="2020-05-28T18:43:35-06:00" level=fatal msg="failed to publish" error="error marshalling to JSON: json: error calling MarshalJSON for type *metric.Set: json: unsupported value: NaN"

Any suggestions?

**Comment by paologallinaharbur** [comment]
The code has been merged to master, but the patch has not been released yet
