### ISSUE TITLE
configured type of disk

### ISSUE THREAD

**Issue by sdeedee** [newrelic/nri-vsphere#79]
In some cases it's important if users add extra disks to a vm they choose the correct type of disk (thin/thick) 
If we have disk type as an attribute in the VM Sample then we can create alerts on specific/all vm's with an inappropriate type of disk.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
