### ISSUE TITLE
Performance metrics not being scraped 

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-vsphere#80]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

Some performance metrics that are available in vCenter are not being pulled by the integration, even if is listed in the `vsphere-performance.metrics` file.

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
Some performance metrics that are available in vCenter are not being pulled by the integration, even if is listed in the `vsphere-performance.metrics` file.
As an example the metric counter `datastore.datastoreReadIops.latest` is available if scraped used `govc` 
```
$ govc metric.sample '/Prod DC/host/192.168.0.200/192.168.0.200' datastore.datastoreReadIops.latest
192.168.0.200  5e45e199-df2bcfdd-4101-00d8619f8752  datastore.datastoreReadIops.latest    0,7,0,3,5,24  num
```
And also is listed in the available metrics when the integration is run with the flag `--log_available_counters`.
`INFO[0008] datastore.datastoreReadIops.latest [1] Storage DRS datastore read I/O rate `

But when running the integration with the performance metric collection activated is not being collected
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
Metric `perf.datastore.datastoreReadIops.latest` is reported in the `VSphereHostSample` Sample

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by paologallinaharbur** [comment]
When creating the request the `instance` field is left blank.

If I retrive the perf metrics available directly from the host the instance field is not empty anymore

Related issue https://github.com/cblomart/vsphere-graphite/issues/44
