### ISSUE TITLE
NSX support

### ISSUE THREAD

**Issue by benohara** [newrelic/nri-vsphere#87]
## Is your feature request related to a problem? Please describe.
Allow monitoring of nsx managers, controllers, edges etc within new relic

## Feature Description
Within vsphere you can see the status of various nsx components, queried via the nsx API I think.  Is it possible to collect data and the status of nsx components.  VMware have a nsx go module.

## Describe Alternatives
Maybe a seperate integration or calling the API with flex, bit as it's tied to vsphere itayne better to collect all the data centrally.

## Additional context
None

## Priority
Really want

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
