### ISSUE TITLE
CLONE - Collect Mount-Level Guest Disk Usage

### ISSUE THREAD

**Issue by kolanos** [newrelic/nri-vsphere#98]
## Is your feature request related to a problem? Please describe.

Customer manages ~6,000 VMs and would like to alert on mount-level disk usage for the guest.

## Feature Description

Collect mount-level disk usage for the guest. This [appears to be possible](https://code.vmware.com/apis/704/vsphere/vim.vm.GuestInfo.DiskInfo.html) via the vSphere API.

## Describe Alternatives

Have suggested installing the infra agent on each VM to collect `StorageSample` metrics. This solution has been rejected due to scale and complexity. Customer is currently using [Truesight](https://www.bmc.com/it-solutions/truesight.html) which offers this level of granularity.

## Priority
 
Blocker

**Comment by paologallinaharbur** [comment]
It seems to be exposed, therefore it should be possible to include that as well https://vdc-repo.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055[…]/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.vm.GuestInfo.html



we are already fetching guestinfo, therefore the load shouldn’t increase 

![image](https://user-images.githubusercontent.com/43335750/123451128-b5d42500-d5dd-11eb-949b-9c1acad556e9.png)

**Comment by paologallinaharbur** [comment]
@kolanos Would make sense to provide a aggregated value computing the % free space of the sum of the disk Pr VM?

Otherwise it could be complex to provide the data due to the 1toMany relation between vm and disks

**Comment by kolanos** [comment]
@paologallinaharbur The customer specifically wants mount-level granularity. Something similar to what [StorageSample](https://docs.newrelic.com/attribute-dictionary/?attribute_name=&events_tids%5B%5D=8407&event=StorageSample) provides, which includes mount-level metrics. They used `df -h` as an example of what kind of metrics they're looking for. So it sounds like they're not as interested in an aggregation of guest disk usage, but I can see that being useful for other use cases.
